apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-assessment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-assessment
  template:
    metadata:
      labels:
        app: devops-assessment
    spec:
      containers:
        - name: devops-assessment-container
          image: 'rishithamarri/devops-assessment:main-b86dba310b6cbeba37abfde44c5f527796f986d2'
          ports:
            - containerPort: 80
          imagePullPolicy: Always
